### ISSUE TITLE
People affected 

### ISSUE THREAD

**Issue by Dimitrismentis** [global-electrification-platform/explorer#144] opened 2019-04-23 08:38 UTC
To me the term "affected" is not clear. Are we referring to total or new connections? People connected or just People sound better.

**Comment by bpstewar** [comment] 2019-05-08 17:11
This is a problem on both the summary charts on the right-side and when querying individual settlements - without know total populations, we cannot infer  much about these areas. Both need total population information included

**Comment by vgeorge** [comment] 2019-05-17 13:23
This issue now seems to be a duplicate of https://github.com/developmentseed/gep-explorer/issues/134, closing.

**Comment by vgeorge** [comment] 2019-06-05 12:03
As the issue #134 is not only regarding this label change, I'll keep this open for follow up independently.

**Comment by vgeorge** [comment] 2019-08-09 11:18
The label was changed to the suggested terminology, I'll close this. 

@bpstewar, I've created another issue to address baseline information (https://github.com/global-electrification-platform/explorer/issues/188).

**Closed by vgeorge** 2019-08-09 11:18 UTC
Labels: to review
